// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: user_coupon_info/v1/user_coupon_info.proto

package v1

import (
	reflect "reflect"
	pbentity "shop-goframe-micro-service/app/goods/api/pbentity"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 新增消息定义
type UserCouponInfoCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty" dc:"用户id"`                 // 用户id
	CouponId      uint32                 `protobuf:"varint,2,opt,name=CouponId,proto3" json:"CouponId,omitempty" dc:"优惠券id"`            // 优惠券id
	Status        uint32                 `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty" dc:"状态：0-待使用，1-已使用，2-已过期"` // 状态：0-待使用，1-已使用，2-已过期
	Amount        uint64                 `protobuf:"varint,4,opt,name=Amount,proto3" json:"Amount,omitempty" dc:"优惠金额（单位：分）"`           // 优惠金额（单位：分）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCouponInfoCreateReq) Reset() {
	*x = UserCouponInfoCreateReq{}
	mi := &file_user_coupon_info_v1_user_coupon_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCouponInfoCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCouponInfoCreateReq) ProtoMessage() {}

func (x *UserCouponInfoCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_coupon_info_v1_user_coupon_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCouponInfoCreateReq.ProtoReflect.Descriptor instead.
func (*UserCouponInfoCreateReq) Descriptor() ([]byte, []int) {
	return file_user_coupon_info_v1_user_coupon_info_proto_rawDescGZIP(), []int{0}
}

func (x *UserCouponInfoCreateReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserCouponInfoCreateReq) GetCouponId() uint32 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *UserCouponInfoCreateReq) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserCouponInfoCreateReq) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type UserCouponInfoCreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCouponInfoCreateRes) Reset() {
	*x = UserCouponInfoCreateRes{}
	mi := &file_user_coupon_info_v1_user_coupon_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCouponInfoCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCouponInfoCreateRes) ProtoMessage() {}

func (x *UserCouponInfoCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_coupon_info_v1_user_coupon_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCouponInfoCreateRes.ProtoReflect.Descriptor instead.
func (*UserCouponInfoCreateRes) Descriptor() ([]byte, []int) {
	return file_user_coupon_info_v1_user_coupon_info_proto_rawDescGZIP(), []int{1}
}

func (x *UserCouponInfoCreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserCouponInfoGetListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty" dc:"修改：字段编号必须从1开始递增"` // 修改：字段编号必须从1开始递增
	UserId        uint32                 `protobuf:"varint,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCouponInfoGetListReq) Reset() {
	*x = UserCouponInfoGetListReq{}
	mi := &file_user_coupon_info_v1_user_coupon_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCouponInfoGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCouponInfoGetListReq) ProtoMessage() {}

func (x *UserCouponInfoGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_coupon_info_v1_user_coupon_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCouponInfoGetListReq.ProtoReflect.Descriptor instead.
func (*UserCouponInfoGetListReq) Descriptor() ([]byte, []int) {
	return file_user_coupon_info_v1_user_coupon_info_proto_rawDescGZIP(), []int{2}
}

func (x *UserCouponInfoGetListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *UserCouponInfoGetListReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UserCouponInfoGetListReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserCouponInfoUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                                   //
	UserId        uint32                 `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty" dc:"用户id"`                 // 用户id
	CouponId      uint32                 `protobuf:"varint,3,opt,name=CouponId,proto3" json:"CouponId,omitempty" dc:"优惠券id"`            // 优惠券id
	Status        uint32                 `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty" dc:"状态：0-待使用，1-已使用，2-已过期"` // 状态：0-待使用，1-已使用，2-已过期
	Amount        uint64                 `protobuf:"varint,5,opt,name=Amount,proto3" json:"Amount,omitempty" dc:"优惠金额（单位：分）"`           // 优惠金额（单位：分）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCouponInfoUpdateReq) Reset() {
	*x = UserCouponInfoUpdateReq{}
	mi := &file_user_coupon_info_v1_user_coupon_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCouponInfoUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCouponInfoUpdateReq) ProtoMessage() {}

func (x *UserCouponInfoUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_coupon_info_v1_user_coupon_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCouponInfoUpdateReq.ProtoReflect.Descriptor instead.
func (*UserCouponInfoUpdateReq) Descriptor() ([]byte, []int) {
	return file_user_coupon_info_v1_user_coupon_info_proto_rawDescGZIP(), []int{3}
}

func (x *UserCouponInfoUpdateReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserCouponInfoUpdateReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserCouponInfoUpdateReq) GetCouponId() uint32 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *UserCouponInfoUpdateReq) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserCouponInfoUpdateReq) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type UserCouponInfoUpdateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCouponInfoUpdateRes) Reset() {
	*x = UserCouponInfoUpdateRes{}
	mi := &file_user_coupon_info_v1_user_coupon_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCouponInfoUpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCouponInfoUpdateRes) ProtoMessage() {}

func (x *UserCouponInfoUpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_coupon_info_v1_user_coupon_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCouponInfoUpdateRes.ProtoReflect.Descriptor instead.
func (*UserCouponInfoUpdateRes) Descriptor() ([]byte, []int) {
	return file_user_coupon_info_v1_user_coupon_info_proto_rawDescGZIP(), []int{4}
}

func (x *UserCouponInfoUpdateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserCouponInfoDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCouponInfoDeleteReq) Reset() {
	*x = UserCouponInfoDeleteReq{}
	mi := &file_user_coupon_info_v1_user_coupon_info_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCouponInfoDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCouponInfoDeleteReq) ProtoMessage() {}

func (x *UserCouponInfoDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_coupon_info_v1_user_coupon_info_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCouponInfoDeleteReq.ProtoReflect.Descriptor instead.
func (*UserCouponInfoDeleteReq) Descriptor() ([]byte, []int) {
	return file_user_coupon_info_v1_user_coupon_info_proto_rawDescGZIP(), []int{5}
}

func (x *UserCouponInfoDeleteReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserCouponInfoDeleteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCouponInfoDeleteRes) Reset() {
	*x = UserCouponInfoDeleteRes{}
	mi := &file_user_coupon_info_v1_user_coupon_info_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCouponInfoDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCouponInfoDeleteRes) ProtoMessage() {}

func (x *UserCouponInfoDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_coupon_info_v1_user_coupon_info_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCouponInfoDeleteRes.ProtoReflect.Descriptor instead.
func (*UserCouponInfoDeleteRes) Descriptor() ([]byte, []int) {
	return file_user_coupon_info_v1_user_coupon_info_proto_rawDescGZIP(), []int{6}
}

type UserCouponInfoListResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	List          []*pbentity.UserCouponInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page          uint32                     `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                     `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total         uint32                     `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCouponInfoListResponse) Reset() {
	*x = UserCouponInfoListResponse{}
	mi := &file_user_coupon_info_v1_user_coupon_info_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCouponInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCouponInfoListResponse) ProtoMessage() {}

func (x *UserCouponInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_coupon_info_v1_user_coupon_info_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCouponInfoListResponse.ProtoReflect.Descriptor instead.
func (*UserCouponInfoListResponse) Descriptor() ([]byte, []int) {
	return file_user_coupon_info_v1_user_coupon_info_proto_rawDescGZIP(), []int{7}
}

func (x *UserCouponInfoListResponse) GetList() []*pbentity.UserCouponInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *UserCouponInfoListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *UserCouponInfoListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UserCouponInfoListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UserCouponInfoGetListRes struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Data          *UserCouponInfoListResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCouponInfoGetListRes) Reset() {
	*x = UserCouponInfoGetListRes{}
	mi := &file_user_coupon_info_v1_user_coupon_info_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCouponInfoGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCouponInfoGetListRes) ProtoMessage() {}

func (x *UserCouponInfoGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_coupon_info_v1_user_coupon_info_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCouponInfoGetListRes.ProtoReflect.Descriptor instead.
func (*UserCouponInfoGetListRes) Descriptor() ([]byte, []int) {
	return file_user_coupon_info_v1_user_coupon_info_proto_rawDescGZIP(), []int{8}
}

func (x *UserCouponInfoGetListRes) GetData() *UserCouponInfoListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_user_coupon_info_v1_user_coupon_info_proto protoreflect.FileDescriptor

const file_user_coupon_info_v1_user_coupon_info_proto_rawDesc = "" +
	"\n" +
	"*user_coupon_info/v1/user_coupon_info.proto\x12\x10user_coupon_info\x1a\x1fpbentity/user_coupon_info.proto\"}\n" +
	"\x17UserCouponInfoCreateReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\rR\x06UserId\x12\x1a\n" +
	"\bCouponId\x18\x02 \x01(\rR\bCouponId\x12\x16\n" +
	"\x06Status\x18\x03 \x01(\rR\x06Status\x12\x16\n" +
	"\x06Amount\x18\x04 \x01(\x04R\x06Amount\")\n" +
	"\x17UserCouponInfoCreateRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"Z\n" +
	"\x18UserCouponInfoGetListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x16\n" +
	"\x06UserId\x18\x03 \x01(\rR\x06UserId\"\x8d\x01\n" +
	"\x17UserCouponInfoUpdateReq\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\rR\x02Id\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\rR\x06UserId\x12\x1a\n" +
	"\bCouponId\x18\x03 \x01(\rR\bCouponId\x12\x16\n" +
	"\x06Status\x18\x04 \x01(\rR\x06Status\x12\x16\n" +
	"\x06Amount\x18\x05 \x01(\x04R\x06Amount\")\n" +
	"\x17UserCouponInfoUpdateRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\")\n" +
	"\x17UserCouponInfoDeleteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x19\n" +
	"\x17UserCouponInfoDeleteRes\"\x88\x01\n" +
	"\x1aUserCouponInfoListResponse\x12,\n" +
	"\x04list\x18\x01 \x03(\v2\x18.pbentity.UserCouponInfoR\x04list\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\"\\\n" +
	"\x18UserCouponInfoGetListRes\x12@\n" +
	"\x04data\x18\x01 \x01(\v2,.user_coupon_info.UserCouponInfoListResponseR\x04data2\x9d\x03\n" +
	"\x10user_coupon_info\x12c\n" +
	"\aGetList\x12*.user_coupon_info.UserCouponInfoGetListReq\x1a*.user_coupon_info.UserCouponInfoGetListRes\"\x00\x12`\n" +
	"\x06Create\x12).user_coupon_info.UserCouponInfoCreateReq\x1a).user_coupon_info.UserCouponInfoCreateRes\"\x00\x12`\n" +
	"\x06Update\x12).user_coupon_info.UserCouponInfoUpdateReq\x1a).user_coupon_info.UserCouponInfoUpdateRes\"\x00\x12`\n" +
	"\x06Delete\x12).user_coupon_info.UserCouponInfoDeleteReq\x1a).user_coupon_info.UserCouponInfoDeleteRes\"\x00BHZFshop-goframe-micro-service-refacotor/app/goods/api/user_coupon_info/v1b\x06proto3"

var (
	file_user_coupon_info_v1_user_coupon_info_proto_rawDescOnce sync.Once
	file_user_coupon_info_v1_user_coupon_info_proto_rawDescData []byte
)

func file_user_coupon_info_v1_user_coupon_info_proto_rawDescGZIP() []byte {
	file_user_coupon_info_v1_user_coupon_info_proto_rawDescOnce.Do(func() {
		file_user_coupon_info_v1_user_coupon_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_coupon_info_v1_user_coupon_info_proto_rawDesc), len(file_user_coupon_info_v1_user_coupon_info_proto_rawDesc)))
	})
	return file_user_coupon_info_v1_user_coupon_info_proto_rawDescData
}

var file_user_coupon_info_v1_user_coupon_info_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_user_coupon_info_v1_user_coupon_info_proto_goTypes = []any{
	(*UserCouponInfoCreateReq)(nil),    // 0: user_coupon_info.UserCouponInfoCreateReq
	(*UserCouponInfoCreateRes)(nil),    // 1: user_coupon_info.UserCouponInfoCreateRes
	(*UserCouponInfoGetListReq)(nil),   // 2: user_coupon_info.UserCouponInfoGetListReq
	(*UserCouponInfoUpdateReq)(nil),    // 3: user_coupon_info.UserCouponInfoUpdateReq
	(*UserCouponInfoUpdateRes)(nil),    // 4: user_coupon_info.UserCouponInfoUpdateRes
	(*UserCouponInfoDeleteReq)(nil),    // 5: user_coupon_info.UserCouponInfoDeleteReq
	(*UserCouponInfoDeleteRes)(nil),    // 6: user_coupon_info.UserCouponInfoDeleteRes
	(*UserCouponInfoListResponse)(nil), // 7: user_coupon_info.UserCouponInfoListResponse
	(*UserCouponInfoGetListRes)(nil),   // 8: user_coupon_info.UserCouponInfoGetListRes
	(*pbentity.UserCouponInfo)(nil),    // 9: pbentity.UserCouponInfo
}
var file_user_coupon_info_v1_user_coupon_info_proto_depIdxs = []int32{
	9, // 0: user_coupon_info.UserCouponInfoListResponse.list:type_name -> pbentity.UserCouponInfo
	7, // 1: user_coupon_info.UserCouponInfoGetListRes.data:type_name -> user_coupon_info.UserCouponInfoListResponse
	2, // 2: user_coupon_info.user_coupon_info.GetList:input_type -> user_coupon_info.UserCouponInfoGetListReq
	0, // 3: user_coupon_info.user_coupon_info.Create:input_type -> user_coupon_info.UserCouponInfoCreateReq
	3, // 4: user_coupon_info.user_coupon_info.Update:input_type -> user_coupon_info.UserCouponInfoUpdateReq
	5, // 5: user_coupon_info.user_coupon_info.Delete:input_type -> user_coupon_info.UserCouponInfoDeleteReq
	8, // 6: user_coupon_info.user_coupon_info.GetList:output_type -> user_coupon_info.UserCouponInfoGetListRes
	1, // 7: user_coupon_info.user_coupon_info.Create:output_type -> user_coupon_info.UserCouponInfoCreateRes
	4, // 8: user_coupon_info.user_coupon_info.Update:output_type -> user_coupon_info.UserCouponInfoUpdateRes
	6, // 9: user_coupon_info.user_coupon_info.Delete:output_type -> user_coupon_info.UserCouponInfoDeleteRes
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_coupon_info_v1_user_coupon_info_proto_init() }
func file_user_coupon_info_v1_user_coupon_info_proto_init() {
	if File_user_coupon_info_v1_user_coupon_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_coupon_info_v1_user_coupon_info_proto_rawDesc), len(file_user_coupon_info_v1_user_coupon_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_coupon_info_v1_user_coupon_info_proto_goTypes,
		DependencyIndexes: file_user_coupon_info_v1_user_coupon_info_proto_depIdxs,
		MessageInfos:      file_user_coupon_info_v1_user_coupon_info_proto_msgTypes,
	}.Build()
	File_user_coupon_info_v1_user_coupon_info_proto = out.File
	file_user_coupon_info_v1_user_coupon_info_proto_goTypes = nil
	file_user_coupon_info_v1_user_coupon_info_proto_depIdxs = nil
}
