// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: coupon_info/v1/coupon_info.proto

package v1

import (
	reflect "reflect"
	pbentity "shop-goframe-micro-service/app/goods/api/pbentity"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 新增消息定义
type CouponInfoCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       uint32                 `protobuf:"varint,1,opt,name=GoodsId,proto3" json:"GoodsId,omitempty" dc:"关联商品id（0表示全场通用）"`  // 关联商品id（0表示全场通用）
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty" dc:"优惠券名称"`                   // 优惠券名称
	Type          uint32                 `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty" dc:"优惠券类型：0-新人券，1-活动券，2-其他"` // 优惠券类型：0-新人券，1-活动券，2-其他
	Amount        uint64                 `protobuf:"varint,4,opt,name=Amount,proto3" json:"Amount,omitempty" dc:"优惠金额（单位：分）"`         // 优惠金额（单位：分）
	Deadline      string                 `protobuf:"bytes,5,opt,name=Deadline,proto3" json:"Deadline,omitempty" dc:"过期时间"`            // 过期时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponInfoCreateReq) Reset() {
	*x = CouponInfoCreateReq{}
	mi := &file_coupon_info_v1_coupon_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponInfoCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponInfoCreateReq) ProtoMessage() {}

func (x *CouponInfoCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_info_v1_coupon_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponInfoCreateReq.ProtoReflect.Descriptor instead.
func (*CouponInfoCreateReq) Descriptor() ([]byte, []int) {
	return file_coupon_info_v1_coupon_info_proto_rawDescGZIP(), []int{0}
}

func (x *CouponInfoCreateReq) GetGoodsId() uint32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *CouponInfoCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CouponInfoCreateReq) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CouponInfoCreateReq) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CouponInfoCreateReq) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

type CouponInfoCreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponInfoCreateRes) Reset() {
	*x = CouponInfoCreateRes{}
	mi := &file_coupon_info_v1_coupon_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponInfoCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponInfoCreateRes) ProtoMessage() {}

func (x *CouponInfoCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_info_v1_coupon_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponInfoCreateRes.ProtoReflect.Descriptor instead.
func (*CouponInfoCreateRes) Descriptor() ([]byte, []int) {
	return file_coupon_info_v1_coupon_info_proto_rawDescGZIP(), []int{1}
}

func (x *CouponInfoCreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CouponInfoGetListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty" dc:"修改：字段编号必须从1开始递增"` // 修改：字段编号必须从1开始递增
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponInfoGetListReq) Reset() {
	*x = CouponInfoGetListReq{}
	mi := &file_coupon_info_v1_coupon_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponInfoGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponInfoGetListReq) ProtoMessage() {}

func (x *CouponInfoGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_info_v1_coupon_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponInfoGetListReq.ProtoReflect.Descriptor instead.
func (*CouponInfoGetListReq) Descriptor() ([]byte, []int) {
	return file_coupon_info_v1_coupon_info_proto_rawDescGZIP(), []int{2}
}

func (x *CouponInfoGetListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CouponInfoGetListReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type CouponInfoUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                                 //
	GoodsId       uint32                 `protobuf:"varint,2,opt,name=GoodsId,proto3" json:"GoodsId,omitempty" dc:"关联商品id（0表示全场通用）"`  // 关联商品id（0表示全场通用）
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty" dc:"优惠券名称"`                   // 优惠券名称
	Type          uint32                 `protobuf:"varint,4,opt,name=Type,proto3" json:"Type,omitempty" dc:"优惠券类型：0-新人券，1-活动券，2-其他"` // 优惠券类型：0-新人券，1-活动券，2-其他
	Amount        uint64                 `protobuf:"varint,5,opt,name=Amount,proto3" json:"Amount,omitempty" dc:"优惠金额（单位：分）"`         // 优惠金额（单位：分）
	Deadline      string                 `protobuf:"bytes,6,opt,name=Deadline,proto3" json:"Deadline,omitempty" dc:"过期时间"`            // 过期时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponInfoUpdateReq) Reset() {
	*x = CouponInfoUpdateReq{}
	mi := &file_coupon_info_v1_coupon_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponInfoUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponInfoUpdateReq) ProtoMessage() {}

func (x *CouponInfoUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_info_v1_coupon_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponInfoUpdateReq.ProtoReflect.Descriptor instead.
func (*CouponInfoUpdateReq) Descriptor() ([]byte, []int) {
	return file_coupon_info_v1_coupon_info_proto_rawDescGZIP(), []int{3}
}

func (x *CouponInfoUpdateReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CouponInfoUpdateReq) GetGoodsId() uint32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *CouponInfoUpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CouponInfoUpdateReq) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CouponInfoUpdateReq) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CouponInfoUpdateReq) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

type CouponInfoUpdateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponInfoUpdateRes) Reset() {
	*x = CouponInfoUpdateRes{}
	mi := &file_coupon_info_v1_coupon_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponInfoUpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponInfoUpdateRes) ProtoMessage() {}

func (x *CouponInfoUpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_info_v1_coupon_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponInfoUpdateRes.ProtoReflect.Descriptor instead.
func (*CouponInfoUpdateRes) Descriptor() ([]byte, []int) {
	return file_coupon_info_v1_coupon_info_proto_rawDescGZIP(), []int{4}
}

func (x *CouponInfoUpdateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CouponInfoDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponInfoDeleteReq) Reset() {
	*x = CouponInfoDeleteReq{}
	mi := &file_coupon_info_v1_coupon_info_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponInfoDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponInfoDeleteReq) ProtoMessage() {}

func (x *CouponInfoDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_info_v1_coupon_info_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponInfoDeleteReq.ProtoReflect.Descriptor instead.
func (*CouponInfoDeleteReq) Descriptor() ([]byte, []int) {
	return file_coupon_info_v1_coupon_info_proto_rawDescGZIP(), []int{5}
}

func (x *CouponInfoDeleteReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CouponInfoDeleteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponInfoDeleteRes) Reset() {
	*x = CouponInfoDeleteRes{}
	mi := &file_coupon_info_v1_coupon_info_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponInfoDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponInfoDeleteRes) ProtoMessage() {}

func (x *CouponInfoDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_info_v1_coupon_info_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponInfoDeleteRes.ProtoReflect.Descriptor instead.
func (*CouponInfoDeleteRes) Descriptor() ([]byte, []int) {
	return file_coupon_info_v1_coupon_info_proto_rawDescGZIP(), []int{6}
}

type CouponInfoListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*pbentity.CouponInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total         uint32                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponInfoListResponse) Reset() {
	*x = CouponInfoListResponse{}
	mi := &file_coupon_info_v1_coupon_info_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponInfoListResponse) ProtoMessage() {}

func (x *CouponInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_info_v1_coupon_info_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponInfoListResponse.ProtoReflect.Descriptor instead.
func (*CouponInfoListResponse) Descriptor() ([]byte, []int) {
	return file_coupon_info_v1_coupon_info_proto_rawDescGZIP(), []int{7}
}

func (x *CouponInfoListResponse) GetList() []*pbentity.CouponInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *CouponInfoListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CouponInfoListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CouponInfoListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CouponInfoGetListRes struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Data          *CouponInfoListResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponInfoGetListRes) Reset() {
	*x = CouponInfoGetListRes{}
	mi := &file_coupon_info_v1_coupon_info_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponInfoGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponInfoGetListRes) ProtoMessage() {}

func (x *CouponInfoGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_info_v1_coupon_info_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponInfoGetListRes.ProtoReflect.Descriptor instead.
func (*CouponInfoGetListRes) Descriptor() ([]byte, []int) {
	return file_coupon_info_v1_coupon_info_proto_rawDescGZIP(), []int{8}
}

func (x *CouponInfoGetListRes) GetData() *CouponInfoListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_coupon_info_v1_coupon_info_proto protoreflect.FileDescriptor

const file_coupon_info_v1_coupon_info_proto_rawDesc = "" +
	"\n" +
	" coupon_info/v1/coupon_info.proto\x12\vcoupon_info\x1a\x1apbentity/coupon_info.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x01\n" +
	"\x13CouponInfoCreateReq\x12\x18\n" +
	"\aGoodsId\x18\x01 \x01(\rR\aGoodsId\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Type\x18\x03 \x01(\rR\x04Type\x12\x16\n" +
	"\x06Amount\x18\x04 \x01(\x04R\x06Amount\x12\x1a\n" +
	"\bDeadline\x18\x05 \x01(\tR\bDeadline\"%\n" +
	"\x13CouponInfoCreateRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\">\n" +
	"\x14CouponInfoGetListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\"\x9b\x01\n" +
	"\x13CouponInfoUpdateReq\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\rR\x02Id\x12\x18\n" +
	"\aGoodsId\x18\x02 \x01(\rR\aGoodsId\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Type\x18\x04 \x01(\rR\x04Type\x12\x16\n" +
	"\x06Amount\x18\x05 \x01(\x04R\x06Amount\x12\x1a\n" +
	"\bDeadline\x18\x06 \x01(\tR\bDeadline\"%\n" +
	"\x13CouponInfoUpdateRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"%\n" +
	"\x13CouponInfoDeleteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x15\n" +
	"\x13CouponInfoDeleteRes\"\x80\x01\n" +
	"\x16CouponInfoListResponse\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.pbentity.CouponInfoR\x04list\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\"O\n" +
	"\x14CouponInfoGetListRes\x127\n" +
	"\x04data\x18\x01 \x01(\v2#.coupon_info.CouponInfoListResponseR\x04data2\xd0\x02\n" +
	"\vcoupon_info\x12Q\n" +
	"\aGetList\x12!.coupon_info.CouponInfoGetListReq\x1a!.coupon_info.CouponInfoGetListRes\"\x00\x12N\n" +
	"\x06Create\x12 .coupon_info.CouponInfoCreateReq\x1a .coupon_info.CouponInfoCreateRes\"\x00\x12N\n" +
	"\x06Update\x12 .coupon_info.CouponInfoUpdateReq\x1a .coupon_info.CouponInfoUpdateRes\"\x00\x12N\n" +
	"\x06Delete\x12 .coupon_info.CouponInfoDeleteReq\x1a .coupon_info.CouponInfoDeleteRes\"\x00BCZAshop-goframe-micro-service-refacotor/app/goods/api/coupon_info/v1b\x06proto3"

var (
	file_coupon_info_v1_coupon_info_proto_rawDescOnce sync.Once
	file_coupon_info_v1_coupon_info_proto_rawDescData []byte
)

func file_coupon_info_v1_coupon_info_proto_rawDescGZIP() []byte {
	file_coupon_info_v1_coupon_info_proto_rawDescOnce.Do(func() {
		file_coupon_info_v1_coupon_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coupon_info_v1_coupon_info_proto_rawDesc), len(file_coupon_info_v1_coupon_info_proto_rawDesc)))
	})
	return file_coupon_info_v1_coupon_info_proto_rawDescData
}

var file_coupon_info_v1_coupon_info_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_coupon_info_v1_coupon_info_proto_goTypes = []any{
	(*CouponInfoCreateReq)(nil),    // 0: coupon_info.CouponInfoCreateReq
	(*CouponInfoCreateRes)(nil),    // 1: coupon_info.CouponInfoCreateRes
	(*CouponInfoGetListReq)(nil),   // 2: coupon_info.CouponInfoGetListReq
	(*CouponInfoUpdateReq)(nil),    // 3: coupon_info.CouponInfoUpdateReq
	(*CouponInfoUpdateRes)(nil),    // 4: coupon_info.CouponInfoUpdateRes
	(*CouponInfoDeleteReq)(nil),    // 5: coupon_info.CouponInfoDeleteReq
	(*CouponInfoDeleteRes)(nil),    // 6: coupon_info.CouponInfoDeleteRes
	(*CouponInfoListResponse)(nil), // 7: coupon_info.CouponInfoListResponse
	(*CouponInfoGetListRes)(nil),   // 8: coupon_info.CouponInfoGetListRes
	(*pbentity.CouponInfo)(nil),    // 9: pbentity.CouponInfo
}
var file_coupon_info_v1_coupon_info_proto_depIdxs = []int32{
	9, // 0: coupon_info.CouponInfoListResponse.list:type_name -> pbentity.CouponInfo
	7, // 1: coupon_info.CouponInfoGetListRes.data:type_name -> coupon_info.CouponInfoListResponse
	2, // 2: coupon_info.coupon_info.GetList:input_type -> coupon_info.CouponInfoGetListReq
	0, // 3: coupon_info.coupon_info.Create:input_type -> coupon_info.CouponInfoCreateReq
	3, // 4: coupon_info.coupon_info.Update:input_type -> coupon_info.CouponInfoUpdateReq
	5, // 5: coupon_info.coupon_info.Delete:input_type -> coupon_info.CouponInfoDeleteReq
	8, // 6: coupon_info.coupon_info.GetList:output_type -> coupon_info.CouponInfoGetListRes
	1, // 7: coupon_info.coupon_info.Create:output_type -> coupon_info.CouponInfoCreateRes
	4, // 8: coupon_info.coupon_info.Update:output_type -> coupon_info.CouponInfoUpdateRes
	6, // 9: coupon_info.coupon_info.Delete:output_type -> coupon_info.CouponInfoDeleteRes
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_coupon_info_v1_coupon_info_proto_init() }
func file_coupon_info_v1_coupon_info_proto_init() {
	if File_coupon_info_v1_coupon_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coupon_info_v1_coupon_info_proto_rawDesc), len(file_coupon_info_v1_coupon_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coupon_info_v1_coupon_info_proto_goTypes,
		DependencyIndexes: file_coupon_info_v1_coupon_info_proto_depIdxs,
		MessageInfos:      file_coupon_info_v1_coupon_info_proto_msgTypes,
	}.Build()
	File_coupon_info_v1_coupon_info_proto = out.File
	file_coupon_info_v1_coupon_info_proto_goTypes = nil
	file_coupon_info_v1_coupon_info_proto_depIdxs = nil
}
