// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: praise_info/v1/praise_info.proto

package v1

import (
	reflect "reflect"
	pbentity "shop-goframe-micro-service/app/interaction/api/pbentity"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 增（因为这个业务是需要登录鉴权的，所以可以不需要UserId，可以直接从登录的账号获取）
type PraiseInfoCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      uint32                 `protobuf:"varint,1,opt,name=ObjectId,proto3" json:"ObjectId,omitempty" dc:"对象id"` //对象id
	Type          uint32                 `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty" dc:"点赞类型：1商品 2文章"` //点赞类型：1商品 2文章
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PraiseInfoCreateReq) Reset() {
	*x = PraiseInfoCreateReq{}
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PraiseInfoCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PraiseInfoCreateReq) ProtoMessage() {}

func (x *PraiseInfoCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PraiseInfoCreateReq.ProtoReflect.Descriptor instead.
func (*PraiseInfoCreateReq) Descriptor() ([]byte, []int) {
	return file_praise_info_v1_praise_info_proto_rawDescGZIP(), []int{0}
}

func (x *PraiseInfoCreateReq) GetObjectId() uint32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *PraiseInfoCreateReq) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type PraiseInfoCreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PraiseInfoCreateRes) Reset() {
	*x = PraiseInfoCreateRes{}
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PraiseInfoCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PraiseInfoCreateRes) ProtoMessage() {}

func (x *PraiseInfoCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PraiseInfoCreateRes.ProtoReflect.Descriptor instead.
func (*PraiseInfoCreateRes) Descriptor() ([]byte, []int) {
	return file_praise_info_v1_praise_info_proto_rawDescGZIP(), []int{1}
}

func (x *PraiseInfoCreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 删
type PraiseInfoDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	ObjectId      uint32                 `protobuf:"varint,2,opt,name=ObjectId,proto3" json:"ObjectId,omitempty" dc:"对象id"` //对象id
	Type          uint32                 `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty" dc:"点赞类型：1商品 2文章"` //点赞类型：1商品 2文章
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PraiseInfoDeleteReq) Reset() {
	*x = PraiseInfoDeleteReq{}
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PraiseInfoDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PraiseInfoDeleteReq) ProtoMessage() {}

func (x *PraiseInfoDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PraiseInfoDeleteReq.ProtoReflect.Descriptor instead.
func (*PraiseInfoDeleteReq) Descriptor() ([]byte, []int) {
	return file_praise_info_v1_praise_info_proto_rawDescGZIP(), []int{2}
}

func (x *PraiseInfoDeleteReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PraiseInfoDeleteReq) GetObjectId() uint32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *PraiseInfoDeleteReq) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type PraiseInfoDeleteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PraiseInfoDeleteRes) Reset() {
	*x = PraiseInfoDeleteRes{}
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PraiseInfoDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PraiseInfoDeleteRes) ProtoMessage() {}

func (x *PraiseInfoDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PraiseInfoDeleteRes.ProtoReflect.Descriptor instead.
func (*PraiseInfoDeleteRes) Descriptor() ([]byte, []int) {
	return file_praise_info_v1_praise_info_proto_rawDescGZIP(), []int{3}
}

func (x *PraiseInfoDeleteRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 查
type PraiseInfoGetListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty" dc:"字段编号必须从1开始递增"` //字段编号必须从1开始递增
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PraiseInfoGetListReq) Reset() {
	*x = PraiseInfoGetListReq{}
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PraiseInfoGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PraiseInfoGetListReq) ProtoMessage() {}

func (x *PraiseInfoGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PraiseInfoGetListReq.ProtoReflect.Descriptor instead.
func (*PraiseInfoGetListReq) Descriptor() ([]byte, []int) {
	return file_praise_info_v1_praise_info_proto_rawDescGZIP(), []int{4}
}

func (x *PraiseInfoGetListReq) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PraiseInfoGetListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PraiseInfoGetListReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PraiseInfoGetListRes struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Data          *PraiseInfoListResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PraiseInfoGetListRes) Reset() {
	*x = PraiseInfoGetListRes{}
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PraiseInfoGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PraiseInfoGetListRes) ProtoMessage() {}

func (x *PraiseInfoGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PraiseInfoGetListRes.ProtoReflect.Descriptor instead.
func (*PraiseInfoGetListRes) Descriptor() ([]byte, []int) {
	return file_praise_info_v1_praise_info_proto_rawDescGZIP(), []int{5}
}

func (x *PraiseInfoGetListRes) GetData() *PraiseInfoListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type PraiseInfoListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*pbentity.PraiseInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty" dc:"收藏信息列表"`  //收藏信息列表
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty" dc:"当前页码"`   //当前页码
	Size          uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty" dc:"每页大小"`   //每页大小
	Total         uint32                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty" dc:"总记录数"` //总记录数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PraiseInfoListResponse) Reset() {
	*x = PraiseInfoListResponse{}
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PraiseInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PraiseInfoListResponse) ProtoMessage() {}

func (x *PraiseInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PraiseInfoListResponse.ProtoReflect.Descriptor instead.
func (*PraiseInfoListResponse) Descriptor() ([]byte, []int) {
	return file_praise_info_v1_praise_info_proto_rawDescGZIP(), []int{6}
}

func (x *PraiseInfoListResponse) GetList() []*pbentity.PraiseInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *PraiseInfoListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PraiseInfoListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PraiseInfoListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_praise_info_v1_praise_info_proto protoreflect.FileDescriptor

const file_praise_info_v1_praise_info_proto_rawDesc = "" +
	"\n" +
	" praise_info/v1/praise_info.proto\x12\vpraise_info\x1a\x1apbentity/praise_info.proto\"E\n" +
	"\x13PraiseInfoCreateReq\x12\x1a\n" +
	"\bObjectId\x18\x01 \x01(\rR\bObjectId\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\rR\x04Type\"%\n" +
	"\x13PraiseInfoCreateRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"U\n" +
	"\x13PraiseInfoDeleteReq\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\rR\x02Id\x12\x1a\n" +
	"\bObjectId\x18\x02 \x01(\rR\bObjectId\x12\x12\n" +
	"\x04Type\x18\x03 \x01(\rR\x04Type\"%\n" +
	"\x13PraiseInfoDeleteRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"R\n" +
	"\x14PraiseInfoGetListReq\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\"O\n" +
	"\x14PraiseInfoGetListRes\x127\n" +
	"\x04data\x18\x01 \x01(\v2#.praise_info.PraiseInfoListResponseR\x04data\"\x80\x01\n" +
	"\x16PraiseInfoListResponse\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.pbentity.PraiseInfoR\x04list\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total2\x80\x02\n" +
	"\vpraise_info\x12N\n" +
	"\x06Create\x12 .praise_info.PraiseInfoCreateReq\x1a .praise_info.PraiseInfoCreateRes\"\x00\x12N\n" +
	"\x06Delete\x12 .praise_info.PraiseInfoDeleteReq\x1a .praise_info.PraiseInfoDeleteRes\"\x00\x12Q\n" +
	"\aGetList\x12!.praise_info.PraiseInfoGetListReq\x1a!.praise_info.PraiseInfoGetListRes\"\x00B+Z)app/user/manifest/protobuf/praise_info/v1b\x06proto3"

var (
	file_praise_info_v1_praise_info_proto_rawDescOnce sync.Once
	file_praise_info_v1_praise_info_proto_rawDescData []byte
)

func file_praise_info_v1_praise_info_proto_rawDescGZIP() []byte {
	file_praise_info_v1_praise_info_proto_rawDescOnce.Do(func() {
		file_praise_info_v1_praise_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_praise_info_v1_praise_info_proto_rawDesc), len(file_praise_info_v1_praise_info_proto_rawDesc)))
	})
	return file_praise_info_v1_praise_info_proto_rawDescData
}

var file_praise_info_v1_praise_info_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_praise_info_v1_praise_info_proto_goTypes = []any{
	(*PraiseInfoCreateReq)(nil),    // 0: praise_info.PraiseInfoCreateReq
	(*PraiseInfoCreateRes)(nil),    // 1: praise_info.PraiseInfoCreateRes
	(*PraiseInfoDeleteReq)(nil),    // 2: praise_info.PraiseInfoDeleteReq
	(*PraiseInfoDeleteRes)(nil),    // 3: praise_info.PraiseInfoDeleteRes
	(*PraiseInfoGetListReq)(nil),   // 4: praise_info.PraiseInfoGetListReq
	(*PraiseInfoGetListRes)(nil),   // 5: praise_info.PraiseInfoGetListRes
	(*PraiseInfoListResponse)(nil), // 6: praise_info.PraiseInfoListResponse
	(*pbentity.PraiseInfo)(nil),    // 7: pbentity.PraiseInfo
}
var file_praise_info_v1_praise_info_proto_depIdxs = []int32{
	6, // 0: praise_info.PraiseInfoGetListRes.data:type_name -> praise_info.PraiseInfoListResponse
	7, // 1: praise_info.PraiseInfoListResponse.list:type_name -> pbentity.PraiseInfo
	0, // 2: praise_info.praise_info.Create:input_type -> praise_info.PraiseInfoCreateReq
	2, // 3: praise_info.praise_info.Delete:input_type -> praise_info.PraiseInfoDeleteReq
	4, // 4: praise_info.praise_info.GetList:input_type -> praise_info.PraiseInfoGetListReq
	1, // 5: praise_info.praise_info.Create:output_type -> praise_info.PraiseInfoCreateRes
	3, // 6: praise_info.praise_info.Delete:output_type -> praise_info.PraiseInfoDeleteRes
	5, // 7: praise_info.praise_info.GetList:output_type -> praise_info.PraiseInfoGetListRes
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_praise_info_v1_praise_info_proto_init() }
func file_praise_info_v1_praise_info_proto_init() {
	if File_praise_info_v1_praise_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_praise_info_v1_praise_info_proto_rawDesc), len(file_praise_info_v1_praise_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_praise_info_v1_praise_info_proto_goTypes,
		DependencyIndexes: file_praise_info_v1_praise_info_proto_depIdxs,
		MessageInfos:      file_praise_info_v1_praise_info_proto_msgTypes,
	}.Build()
	File_praise_info_v1_praise_info_proto = out.File
	file_praise_info_v1_praise_info_proto_goTypes = nil
	file_praise_info_v1_praise_info_proto_depIdxs = nil
}
