// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: pbentity/cart_info.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"购物车表"`           // 购物车表
	UserId        int32                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`             //
	GoodsId       int32                  `protobuf:"varint,3,opt,name=GoodsId,proto3" json:"GoodsId,omitempty" dc:"商品id"` // 商品id
	Count         int32                  `protobuf:"varint,4,opt,name=Count,proto3" json:"Count,omitempty" dc:"商品数量"`     // 商品数量
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`        //
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`        //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartInfo) Reset() {
	*x = CartInfo{}
	mi := &file_pbentity_cart_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartInfo) ProtoMessage() {}

func (x *CartInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_cart_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartInfo.ProtoReflect.Descriptor instead.
func (*CartInfo) Descriptor() ([]byte, []int) {
	return file_pbentity_cart_info_proto_rawDescGZIP(), []int{0}
}

func (x *CartInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartInfo) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CartInfo) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *CartInfo) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CartInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CartInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_pbentity_cart_info_proto protoreflect.FileDescriptor

const file_pbentity_cart_info_proto_rawDesc = "" +
	"\n" +
	"\x18pbentity/cart_info.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd6\x01\n" +
	"\bCartInfo\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x05R\x06UserId\x12\x18\n" +
	"\aGoodsId\x18\x03 \x01(\x05R\aGoodsId\x12\x14\n" +
	"\x05Count\x18\x04 \x01(\x05R\x05Count\x128\n" +
	"\tCreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAtB3Z1shop-goframe-micro-service/app/goods/api/pbentityb\x06proto3"

var (
	file_pbentity_cart_info_proto_rawDescOnce sync.Once
	file_pbentity_cart_info_proto_rawDescData []byte
)

func file_pbentity_cart_info_proto_rawDescGZIP() []byte {
	file_pbentity_cart_info_proto_rawDescOnce.Do(func() {
		file_pbentity_cart_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_cart_info_proto_rawDesc), len(file_pbentity_cart_info_proto_rawDesc)))
	})
	return file_pbentity_cart_info_proto_rawDescData
}

var file_pbentity_cart_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_cart_info_proto_goTypes = []any{
	(*CartInfo)(nil),              // 0: pbentity.CartInfo
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_cart_info_proto_depIdxs = []int32{
	1, // 0: pbentity.CartInfo.CreatedAt:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.CartInfo.UpdatedAt:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pbentity_cart_info_proto_init() }
func file_pbentity_cart_info_proto_init() {
	if File_pbentity_cart_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_cart_info_proto_rawDesc), len(file_pbentity_cart_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_cart_info_proto_goTypes,
		DependencyIndexes: file_pbentity_cart_info_proto_depIdxs,
		MessageInfos:      file_pbentity_cart_info_proto_msgTypes,
	}.Build()
	File_pbentity_cart_info_proto = out.File
	file_pbentity_cart_info_proto_goTypes = nil
	file_pbentity_cart_info_proto_depIdxs = nil
}
