// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: pbentity/user_coupon_info.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserCouponInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                                   //
	UserId        int32                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty" dc:"用户id"`                 // 用户id
	CouponId      int32                  `protobuf:"varint,3,opt,name=CouponId,proto3" json:"CouponId,omitempty" dc:"优惠券id"`            // 优惠券id
	Status        int32                  `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty" dc:"状态：0-待使用，1-已使用，2-已过期"` // 状态：0-待使用，1-已使用，2-已过期
	Amount        int32                  `protobuf:"varint,5,opt,name=Amount,proto3" json:"Amount,omitempty" dc:"优惠金额（单位：分）"`           // 优惠金额（单位：分）
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty" dc:"创建时间"`            // 创建时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty" dc:"更新时间"`            // 更新时间
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty" dc:"删除时间（软删除）"`       // 删除时间（软删除）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCouponInfo) Reset() {
	*x = UserCouponInfo{}
	mi := &file_pbentity_user_coupon_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCouponInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCouponInfo) ProtoMessage() {}

func (x *UserCouponInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_user_coupon_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCouponInfo.ProtoReflect.Descriptor instead.
func (*UserCouponInfo) Descriptor() ([]byte, []int) {
	return file_pbentity_user_coupon_info_proto_rawDescGZIP(), []int{0}
}

func (x *UserCouponInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserCouponInfo) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserCouponInfo) GetCouponId() int32 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *UserCouponInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserCouponInfo) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UserCouponInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserCouponInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UserCouponInfo) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_pbentity_user_coupon_info_proto protoreflect.FileDescriptor

const file_pbentity_user_coupon_info_proto_rawDesc = "" +
	"\n" +
	"\x1fpbentity/user_coupon_info.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x02\n" +
	"\x0eUserCouponInfo\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x05R\x06UserId\x12\x1a\n" +
	"\bCouponId\x18\x03 \x01(\x05R\bCouponId\x12\x16\n" +
	"\x06Status\x18\x04 \x01(\x05R\x06Status\x12\x16\n" +
	"\x06Amount\x18\x05 \x01(\x05R\x06Amount\x128\n" +
	"\tCreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x128\n" +
	"\tDeletedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAtB3Z1shop-goframe-micro-service/app/goods/api/pbentityb\x06proto3"

var (
	file_pbentity_user_coupon_info_proto_rawDescOnce sync.Once
	file_pbentity_user_coupon_info_proto_rawDescData []byte
)

func file_pbentity_user_coupon_info_proto_rawDescGZIP() []byte {
	file_pbentity_user_coupon_info_proto_rawDescOnce.Do(func() {
		file_pbentity_user_coupon_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_user_coupon_info_proto_rawDesc), len(file_pbentity_user_coupon_info_proto_rawDesc)))
	})
	return file_pbentity_user_coupon_info_proto_rawDescData
}

var file_pbentity_user_coupon_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_user_coupon_info_proto_goTypes = []any{
	(*UserCouponInfo)(nil),        // 0: pbentity.UserCouponInfo
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_user_coupon_info_proto_depIdxs = []int32{
	1, // 0: pbentity.UserCouponInfo.CreatedAt:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.UserCouponInfo.UpdatedAt:type_name -> google.protobuf.Timestamp
	1, // 2: pbentity.UserCouponInfo.DeletedAt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pbentity_user_coupon_info_proto_init() }
func file_pbentity_user_coupon_info_proto_init() {
	if File_pbentity_user_coupon_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_user_coupon_info_proto_rawDesc), len(file_pbentity_user_coupon_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_user_coupon_info_proto_goTypes,
		DependencyIndexes: file_pbentity_user_coupon_info_proto_depIdxs,
		MessageInfos:      file_pbentity_user_coupon_info_proto_msgTypes,
	}.Build()
	File_pbentity_user_coupon_info_proto = out.File
	file_pbentity_user_coupon_info_proto_goTypes = nil
	file_pbentity_user_coupon_info_proto_depIdxs = nil
}
