// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: cart_info/v1/cart_info.proto

package v1

import (
	reflect "reflect"
	pbentity "shop-goframe-micro-service/app/goods/api/pbentity"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 新增消息定义
type CartInfoCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       uint32                 `protobuf:"varint,1,opt,name=GoodsId,proto3" json:"GoodsId,omitempty" dc:"商品id"` // 商品id
	Count         uint32                 `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty" dc:"商品数量"`     // 商品数量
	UserId        uint32                 `protobuf:"varint,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartInfoCreateReq) Reset() {
	*x = CartInfoCreateReq{}
	mi := &file_cart_info_v1_cart_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartInfoCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartInfoCreateReq) ProtoMessage() {}

func (x *CartInfoCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_cart_info_v1_cart_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartInfoCreateReq.ProtoReflect.Descriptor instead.
func (*CartInfoCreateReq) Descriptor() ([]byte, []int) {
	return file_cart_info_v1_cart_info_proto_rawDescGZIP(), []int{0}
}

func (x *CartInfoCreateReq) GetGoodsId() uint32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *CartInfoCreateReq) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CartInfoCreateReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CartInfoCreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartInfoCreateRes) Reset() {
	*x = CartInfoCreateRes{}
	mi := &file_cart_info_v1_cart_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartInfoCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartInfoCreateRes) ProtoMessage() {}

func (x *CartInfoCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_cart_info_v1_cart_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartInfoCreateRes.ProtoReflect.Descriptor instead.
func (*CartInfoCreateRes) Descriptor() ([]byte, []int) {
	return file_cart_info_v1_cart_info_proto_rawDescGZIP(), []int{1}
}

func (x *CartInfoCreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CartInfoDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartInfoDeleteReq) Reset() {
	*x = CartInfoDeleteReq{}
	mi := &file_cart_info_v1_cart_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartInfoDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartInfoDeleteReq) ProtoMessage() {}

func (x *CartInfoDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_cart_info_v1_cart_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartInfoDeleteReq.ProtoReflect.Descriptor instead.
func (*CartInfoDeleteReq) Descriptor() ([]byte, []int) {
	return file_cart_info_v1_cart_info_proto_rawDescGZIP(), []int{2}
}

func (x *CartInfoDeleteReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CartInfoDeleteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartInfoDeleteRes) Reset() {
	*x = CartInfoDeleteRes{}
	mi := &file_cart_info_v1_cart_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartInfoDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartInfoDeleteRes) ProtoMessage() {}

func (x *CartInfoDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_cart_info_v1_cart_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartInfoDeleteRes.ProtoReflect.Descriptor instead.
func (*CartInfoDeleteRes) Descriptor() ([]byte, []int) {
	return file_cart_info_v1_cart_info_proto_rawDescGZIP(), []int{3}
}

func (x *CartInfoDeleteRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CartInfoGetListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	UserId        uint32                 `protobuf:"varint,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartInfoGetListReq) Reset() {
	*x = CartInfoGetListReq{}
	mi := &file_cart_info_v1_cart_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartInfoGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartInfoGetListReq) ProtoMessage() {}

func (x *CartInfoGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_cart_info_v1_cart_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartInfoGetListReq.ProtoReflect.Descriptor instead.
func (*CartInfoGetListReq) Descriptor() ([]byte, []int) {
	return file_cart_info_v1_cart_info_proto_rawDescGZIP(), []int{4}
}

func (x *CartInfoGetListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CartInfoGetListReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CartInfoGetListReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CartInfoListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*pbentity.CartInfo   `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total         uint32                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartInfoListResponse) Reset() {
	*x = CartInfoListResponse{}
	mi := &file_cart_info_v1_cart_info_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartInfoListResponse) ProtoMessage() {}

func (x *CartInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_info_v1_cart_info_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartInfoListResponse.ProtoReflect.Descriptor instead.
func (*CartInfoListResponse) Descriptor() ([]byte, []int) {
	return file_cart_info_v1_cart_info_proto_rawDescGZIP(), []int{5}
}

func (x *CartInfoListResponse) GetList() []*pbentity.CartInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *CartInfoListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CartInfoListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CartInfoListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CartInfoGetListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *CartInfoListResponse  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartInfoGetListRes) Reset() {
	*x = CartInfoGetListRes{}
	mi := &file_cart_info_v1_cart_info_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartInfoGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartInfoGetListRes) ProtoMessage() {}

func (x *CartInfoGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_cart_info_v1_cart_info_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartInfoGetListRes.ProtoReflect.Descriptor instead.
func (*CartInfoGetListRes) Descriptor() ([]byte, []int) {
	return file_cart_info_v1_cart_info_proto_rawDescGZIP(), []int{6}
}

func (x *CartInfoGetListRes) GetData() *CartInfoListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_cart_info_v1_cart_info_proto protoreflect.FileDescriptor

const file_cart_info_v1_cart_info_proto_rawDesc = "" +
	"\n" +
	"\x1ccart_info/v1/cart_info.proto\x12\fcart_info.v1\x1a\x18pbentity/cart_info.proto\"[\n" +
	"\x11CartInfoCreateReq\x12\x18\n" +
	"\aGoodsId\x18\x01 \x01(\rR\aGoodsId\x12\x14\n" +
	"\x05Count\x18\x02 \x01(\rR\x05Count\x12\x16\n" +
	"\x06UserId\x18\x03 \x01(\rR\x06UserId\"#\n" +
	"\x11CartInfoCreateRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"#\n" +
	"\x11CartInfoDeleteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"#\n" +
	"\x11CartInfoDeleteRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"T\n" +
	"\x12CartInfoGetListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x16\n" +
	"\x06UserId\x18\x03 \x01(\rR\x06UserId\"|\n" +
	"\x14CartInfoListResponse\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.pbentity.CartInfoR\x04list\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\"L\n" +
	"\x12CartInfoGetListRes\x126\n" +
	"\x04data\x18\x01 \x01(\v2\".cart_info.v1.CartInfoListResponseR\x04data2\xf8\x01\n" +
	"\tcart_info\x12O\n" +
	"\aGetList\x12 .cart_info.v1.CartInfoGetListReq\x1a .cart_info.v1.CartInfoGetListRes\"\x00\x12L\n" +
	"\x06Create\x12\x1f.cart_info.v1.CartInfoCreateReq\x1a\x1f.cart_info.v1.CartInfoCreateRes\"\x00\x12L\n" +
	"\x06Delete\x12\x1f.cart_info.v1.CartInfoDeleteReq\x1a\x1f.cart_info.v1.CartInfoDeleteRes\"\x00BAZ?shop-goframe-micro-service-refacotor/app/goods/api/cart_info/v1b\x06proto3"

var (
	file_cart_info_v1_cart_info_proto_rawDescOnce sync.Once
	file_cart_info_v1_cart_info_proto_rawDescData []byte
)

func file_cart_info_v1_cart_info_proto_rawDescGZIP() []byte {
	file_cart_info_v1_cart_info_proto_rawDescOnce.Do(func() {
		file_cart_info_v1_cart_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cart_info_v1_cart_info_proto_rawDesc), len(file_cart_info_v1_cart_info_proto_rawDesc)))
	})
	return file_cart_info_v1_cart_info_proto_rawDescData
}

var file_cart_info_v1_cart_info_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cart_info_v1_cart_info_proto_goTypes = []any{
	(*CartInfoCreateReq)(nil),    // 0: cart_info.v1.CartInfoCreateReq
	(*CartInfoCreateRes)(nil),    // 1: cart_info.v1.CartInfoCreateRes
	(*CartInfoDeleteReq)(nil),    // 2: cart_info.v1.CartInfoDeleteReq
	(*CartInfoDeleteRes)(nil),    // 3: cart_info.v1.CartInfoDeleteRes
	(*CartInfoGetListReq)(nil),   // 4: cart_info.v1.CartInfoGetListReq
	(*CartInfoListResponse)(nil), // 5: cart_info.v1.CartInfoListResponse
	(*CartInfoGetListRes)(nil),   // 6: cart_info.v1.CartInfoGetListRes
	(*pbentity.CartInfo)(nil),    // 7: pbentity.CartInfo
}
var file_cart_info_v1_cart_info_proto_depIdxs = []int32{
	7, // 0: cart_info.v1.CartInfoListResponse.list:type_name -> pbentity.CartInfo
	5, // 1: cart_info.v1.CartInfoGetListRes.data:type_name -> cart_info.v1.CartInfoListResponse
	4, // 2: cart_info.v1.cart_info.GetList:input_type -> cart_info.v1.CartInfoGetListReq
	0, // 3: cart_info.v1.cart_info.Create:input_type -> cart_info.v1.CartInfoCreateReq
	2, // 4: cart_info.v1.cart_info.Delete:input_type -> cart_info.v1.CartInfoDeleteReq
	6, // 5: cart_info.v1.cart_info.GetList:output_type -> cart_info.v1.CartInfoGetListRes
	1, // 6: cart_info.v1.cart_info.Create:output_type -> cart_info.v1.CartInfoCreateRes
	3, // 7: cart_info.v1.cart_info.Delete:output_type -> cart_info.v1.CartInfoDeleteRes
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cart_info_v1_cart_info_proto_init() }
func file_cart_info_v1_cart_info_proto_init() {
	if File_cart_info_v1_cart_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cart_info_v1_cart_info_proto_rawDesc), len(file_cart_info_v1_cart_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cart_info_v1_cart_info_proto_goTypes,
		DependencyIndexes: file_cart_info_v1_cart_info_proto_depIdxs,
		MessageInfos:      file_cart_info_v1_cart_info_proto_msgTypes,
	}.Build()
	File_cart_info_v1_cart_info_proto = out.File
	file_cart_info_v1_cart_info_proto_goTypes = nil
	file_cart_info_v1_cart_info_proto_depIdxs = nil
}
