// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
	"shop-goframe-micro-service/app/gateway-h5/api/user"
	consignee_info "shop-goframe-micro-service/app/user/api/consignee_info/v1"
	"shop-goframe-micro-service/utility"
)

type ControllerV1 struct {
	ConsigneeInfoClient consignee_info.ConsigneeInfoClient
}

func NewV1() user.IUserV1 {
	var conn = grpcx.Client.MustNewGrpcClientConn("user",
		grpcx.Client.ChainUnary(
			utility.GrpcClientTimeout, //超时处理，避免网络异常导致业务网关无限卡死
		))
	return &ControllerV1{
		ConsigneeInfoClient: consignee_info.NewConsigneeInfoClient(conn),
	}
}
